// Generated by `wrangler types` (the "project types" step, which reads
// wrangler.jsonc and needs no local runtime). Do not hand-edit — re-run
// `npx wrangler types` after any change to wrangler.jsonc's vars/bindings.
//
// NOTE: `wrangler types` also runs a "runtime types" step that shells out
// to the local Workers runtime (workerd), which requires macOS 13.5+ or
// Linux (glibc 2.35+) — this dev machine is on macOS 12.6.0, so that step
// fails and the file isn't written automatically. The interface below is
// wrangler's own real output from the project-types step, copied in by
// hand only because of that local OS gap — not a guessed shape. Re-run
// `npx wrangler types` on a supported OS (or in CI) to regenerate this
// file for real, especially after adding secrets or bindings.
//
// Secrets (GEMINI_API_KEY, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY) are
// set via `wrangler secret put` and don't live in wrangler.jsonc, so they
// don't appear in generated types either — declared by hand below.

interface __BaseEnv_Env {
	RATE_LIMIT_KV: KVNamespace;
	FIREBASE_PROJECT_ID: string;
	FIREBASE_STORAGE_BUCKET: string;
	GEMINI_MODEL: string;
	MATCH_MODEL_VERSION: string;
	SCAM_MODEL_VERSION: string;
	RATE_LIMIT_PER_USER_PER_DAY: string;
}

interface __SecretEnv_Env {
	GEMINI_API_KEY: string;
	FIREBASE_CLIENT_EMAIL: string;
	FIREBASE_PRIVATE_KEY: string;
}

interface Env extends __BaseEnv_Env, __SecretEnv_Env {}
